%dev.quarkus.datasource.dev-ui.allow-sql=true

quarkus.http.auth.form.enabled=true
quarkus.http.auth.form.landing-page=
quarkus.http.auth.form.login-page=
quarkus.http.auth.form.error-page=
quarkus.http.auth.form.http-only-cookie=true
quarkus.http.auth.form.post-location=/user/login
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET, POST, PUT, DELETE
quarkus.http.cors.exposed-headers=Content-Disposition
quarkus.http.cors.access-control-max-age=24H
quarkus.http.cors.access-control-allow-credentials=true